# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Prepare build directory
        run: cmake -E make_directory ${{github.workspace}}/build
      
      - name: Load libraries
        working-directory: ${{github.workspace}}/lib
        run: git submodule update --init --recursive
        
      - name: Configure cmake files
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DTESTS=ON
      
      - name: Build and test
        working-directory: ${{github.workspace}}/build
        run: make -j 2
      
      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: odd_checker
          path: bin/odd_checker
      
      
